spring:
  datasource:
    url: jdbc:mysql://localhost:3307/store?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true
websiteUrl: "http://localhost:3000/"

#  hibernate:
#    ddl-auto: create