spring:
  datasource:
    url: jdbc:mysql://localhost:3307/store?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800


#  hibernate:
#    ddl-auto: create